services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: "2g"
    ports:
      - "4444:4444"

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: ["/zap/zap.sh", "-daemon", "-port", "8080", "-host", "0.0.0.0", "-config", "api.addrs.addr.name=.*", "-config", "api.addrs.addr.regex=true"]
    ports:
      - "8080:8080"
    volumes:
      - ./zap:/zap/wrk

  tests:
    build: .
    working_dir: /app
    depends_on:
      - selenium
      - zap
    environment:
      SELENIDE_REMOTE_URL: http://selenium:4444/wd/hub
      ZAP_HOST: zap
      ZAP_PORT: 8080
    volumes:
      - ./allure-results:/app/allure-results
      - ./target:/app/target
      - ./jmeter:/app/jmeter
